"""
agent/agent.py
--------------

LangGraph-based agent for MindSync.

Workflow:
1. Receive the student's message.
2. Receive authenticated student identity from the API.
3. Send the message to Groq through LangChain.
4. Groq decides whether a tool is required.
5. LangGraph executes the selected tool.
6. Student-specific tools obtain student_id from runtime context.
7. Tool results are returned to Groq.
8. Groq can call additional tools when necessary.
9. When no more tools are required, Groq produces the final answer.
"""

from dataclasses import dataclass
from typing import Annotated, TypedDict

from langchain_groq import ChatGroq

from langchain_core.messages import (
    AIMessage,
    BaseMessage,
    HumanMessage,
    SystemMessage,
)

from langgraph.graph import END, StateGraph
from langgraph.graph.message import add_messages
from langgraph.prebuilt import ToolNode

from app.config import GROQ_API_KEY, GROQ_MODEL
from app.agent.prompts import SYSTEM_PROMPT
from app.agent.tools import TOOLS


# ===================================================================
# RUNTIME CONTEXT
# ===================================================================


@dataclass
class AgentContext:
    """
    Runtime information supplied by the application.

    The student_id comes from the authenticated JWT.
    It is never generated by the LLM.
    """

    student_id: str


# ===================================================================
# MODEL
# ===================================================================


llm = ChatGroq(
    model=GROQ_MODEL,
    groq_api_key=GROQ_API_KEY,
    temperature=0,
)

# Give Groq access to the MindSync tools.
llm_with_tools = llm.bind_tools(TOOLS)


# ===================================================================
# GRAPH STATE
# ===================================================================


class AgentState(TypedDict):
    """
    State maintained by LangGraph during a conversation.
    """

    messages: Annotated[
        list[BaseMessage],
        add_messages,
    ]


# ===================================================================
# AGENT NODE
# ===================================================================


def agent_node(state: AgentState):
    """
    Ask Groq what should happen next.

    Groq may either:
    - produce a normal response, or
    - request one or more tools.

    Student identity is NOT placed in the model-generated
    tool arguments. Student-specific tools receive it through
    LangGraph runtime context.
    """

    messages = [
        SystemMessage(
            content=SYSTEM_PROMPT
        )
    ] + state["messages"]

    response = llm_with_tools.invoke(messages)

    return {
        "messages": [response]
    }


# ===================================================================
# ROUTING
# ===================================================================


def should_continue(state: AgentState):
    """
    Decide whether LangGraph should execute tools or finish.

    If Groq requested a tool:
        route to ToolNode.

    Otherwise:
        finish the graph.
    """

    last_message = state["messages"][-1]

    if isinstance(last_message, AIMessage):

        if last_message.tool_calls:
            return "tools"

    return END


# ===================================================================
# TOOL NODE
# ===================================================================


tool_node = ToolNode(TOOLS)


# ===================================================================
# BUILD LANGGRAPH
# ===================================================================


workflow = StateGraph(
    AgentState,
    context_schema=AgentContext,
)

workflow.add_node(
    "agent",
    agent_node,
)

workflow.add_node(
    "tools",
    tool_node,
)

workflow.set_entry_point("agent")

workflow.add_conditional_edges(
    "agent",
    should_continue,
    {
        "tools": "tools",
        END: END,
    },
)

workflow.add_edge(
    "tools",
    "agent",
)


# Compile the graph.
graph = workflow.compile()


# ===================================================================
# PUBLIC AGENT FUNCTION
# ===================================================================


def run_agent(
    user_message: str,
    conversation_history: list[dict] | None = None,
    student_id: str | None = None,
) -> dict:
    """
    Run the MindSync LangGraph agent.

    Parameters
    ----------
    user_message:
        Current message from the student.

    conversation_history:
        Previous conversation messages.

    student_id:
        Authenticated student ID obtained from the JWT.

    Returns
    -------
    dict
        {
            "reply": str,
            "history": list,
            "tool_calls": list,
            "message_count": int,
            "message_types": list
        }
    """

    # ---------------------------------------------------------------
    # Validate authenticated student identity
    # ---------------------------------------------------------------

    if not student_id or not student_id.strip():

        raise ValueError(
            "Authenticated student identity is required."
        )

    student_id = student_id.strip()

    messages: list[BaseMessage] = []

    # ---------------------------------------------------------------
    # Convert existing history into LangChain messages
    # ---------------------------------------------------------------

    for message in conversation_history or []:

        if not isinstance(message, dict):
            continue

        role = message.get("role")
        content = message.get("content", "")

        if not isinstance(content, str):
            continue

        content = content.strip()

        if not content:
            continue

        if role == "user":

            messages.append(
                HumanMessage(
                    content=content,
                )
            )

        elif role == "assistant":

            messages.append(
                AIMessage(
                    content=content,
                )
            )

    # ---------------------------------------------------------------
    # Add current user message
    # ---------------------------------------------------------------

    messages.append(
        HumanMessage(
            content=user_message,
        )
    )

    # ---------------------------------------------------------------
    # Run LangGraph
    # ---------------------------------------------------------------

    result = graph.invoke(
        {
            "messages": messages,
        },
        context=AgentContext(
            student_id=student_id,
        ),
        config={
            "recursion_limit": 10,
        },
    )

    final_messages = result["messages"]

    # ---------------------------------------------------------------
    # Extract final AI response
    # ---------------------------------------------------------------

    reply = ""

    for message in reversed(final_messages):

        if not isinstance(message, AIMessage):
            continue

        # Ignore AI messages that are requesting tools.
        if message.tool_calls:
            continue

        if isinstance(message.content, str):

            reply = message.content

        elif isinstance(message.content, list):

            text_parts = []

            for block in message.content:

                if (
                    isinstance(block, dict)
                    and block.get("type") == "text"
                ):
                    text_parts.append(
                        block.get("text", "")
                    )

            reply = "".join(text_parts)

        if reply:
            break

    # ---------------------------------------------------------------
    # Collect tool calls
    # ---------------------------------------------------------------

    tool_calls = []

    for message in final_messages:

        if not isinstance(message, AIMessage):
            continue

        for call in message.tool_calls:

            tool_calls.append(
                {
                    "tool": call.get("name"),
                    "input": call.get("args", {}),
                }
            )

    # ---------------------------------------------------------------
    # Build simple conversation history
    # ---------------------------------------------------------------

    history = []

    for message in final_messages:

        if isinstance(message, HumanMessage):

            history.append(
                {
                    "role": "user",
                    "content": message.content,
                }
            )

        elif isinstance(message, AIMessage):

            # Do not expose intermediate tool-call messages
            # as normal assistant responses.
            if message.tool_calls:
                continue

            if isinstance(message.content, str):

                if message.content.strip():

                    history.append(
                        {
                            "role": "assistant",
                            "content": message.content,
                        }
                    )

            elif isinstance(message.content, list):

                text_parts = []

                for block in message.content:

                    if (
                        isinstance(block, dict)
                        and block.get("type") == "text"
                    ):
                        text_parts.append(
                            block.get("text", "")
                        )

                content = "".join(text_parts)

                if content.strip():

                    history.append(
                        {
                            "role": "assistant",
                            "content": content,
                        }
                    )

    # ---------------------------------------------------------------
    # Diagnostic information
    # ---------------------------------------------------------------

    message_types = [
        type(message).__name__
        for message in final_messages
    ]

    # ---------------------------------------------------------------
    # Return result
    # ---------------------------------------------------------------

    return {
        "reply": reply.strip(),
        "history": history,
        "tool_calls": tool_calls,
        "message_count": len(final_messages),
        "message_types": message_types,
    }