"""
app/agent/agent.py
------------------

MindSync LangGraph agent.

Responsibilities:
- Build the LangGraph workflow
- Maintain authenticated student context
- Bind library tools to the LLM
- Force authenticated student IDs
- Execute tools through LangGraph
- Limit conversation history to 15 messages
- Return the final assistant response
"""

from typing import Annotated, TypedDict

from langchain_core.messages import (
    AIMessage,
    BaseMessage,
    HumanMessage,
    SystemMessage,
)

from langgraph.graph import (
    StateGraph,
    END,
)

from langgraph.graph.message import add_messages
from langgraph.prebuilt import ToolNode
from langchain_groq import ChatGroq

from app.config import GROQ_API_KEY, GROQ_MODEL
from app.agent.prompts import SYSTEM_PROMPT
from app.agent.tools import TOOLS


# ============================================================
# CONFIGURATION
# ============================================================

MAX_HISTORY = 15
MAX_RECURSION_LIMIT = 12


# ============================================================
# AUTHENTICATED CONTEXT
# ============================================================

class AgentContext:
    """
    Runtime context containing the authenticated student ID.
    """

    def __init__(self, student_id: str):
        self.student_id = student_id


# ============================================================
# STATE
# ============================================================

class AgentState(TypedDict):
    messages: Annotated[
        list[BaseMessage],
        add_messages
    ]


# ============================================================
# LLM
# ============================================================

llm = ChatGroq(
    api_key=GROQ_API_KEY,
    model=GROQ_MODEL,
    temperature=0,
)

llm_with_tools = llm.bind_tools(TOOLS)


# ============================================================
# STUDENT-SPECIFIC TOOLS
# ============================================================

STUDENT_TOOLS = {
    "borrow_book",
    "return_book",
    "renew_book",
    "reserve_book",
    "cancel_reservation",
    "get_student_borrowings",
    "get_student_fines",
}


# ============================================================
# AGENT NODE
# ============================================================

def agent_node(
    state: AgentState,
):
    """
    Ask the LLM what to do next.
    """

    messages = [
        SystemMessage(
            content=SYSTEM_PROMPT
        )
    ] + state["messages"]

    response = llm_with_tools.invoke(
        messages
    )

    return {
        "messages": [
            response
        ]
    }


# ============================================================
# AUTHENTICATED TOOL CALL SANITIZATION
# ============================================================

def sanitize_tool_calls(
    state: AgentState,
    student_id: str,
):
    """
    Force the authenticated student ID into
    every student-specific tool call.

    The LLM is never trusted to determine
    which student's data should be accessed.
    """

    if not state["messages"]:
        return state

    last_message = state["messages"][-1]

    if not isinstance(
        last_message,
        AIMessage,
    ):
        return state

    tool_calls = getattr(
        last_message,
        "tool_calls",
        None,
    )

    if not tool_calls:
        return state

    for call in tool_calls:

        if not isinstance(
            call,
            dict,
        ):
            continue

        tool_name = call.get(
            "name"
        )

        if tool_name not in STUDENT_TOOLS:
            continue

        args = call.get(
            "args"
        )

        if not isinstance(
            args,
            dict,
        ):
            args = {}

        # Never trust the student ID generated by the LLM.
        args["student_id"] = student_id

        call["args"] = args

    return state


# ============================================================
# AUTHENTICATED AGENT NODE
# ============================================================

def authenticated_agent_node(
    state: AgentState,
    runtime,
):
    """
    Generate an AI response and sanitize
    student-specific tool calls.
    """

    messages = [
        SystemMessage(
            content=SYSTEM_PROMPT
        )
    ] + state["messages"]

    response = llm_with_tools.invoke(
        messages
    )

    # --------------------------------------------------------
    # Get authenticated student ID
    # --------------------------------------------------------

    student_id = None

    try:

        if runtime and hasattr(
            runtime,
            "context",
        ):

            context = runtime.context

            if context and hasattr(
                context,
                "student_id",
            ):

                student_id = (
                    context.student_id
                )

    except Exception:
        student_id = None

    # --------------------------------------------------------
    # Sanitize tool calls
    # --------------------------------------------------------

    if student_id and isinstance(
        response,
        AIMessage,
    ):

        temp_state = {
            "messages": [
                response
            ]
        }

        temp_state = sanitize_tool_calls(
            temp_state,
            student_id,
        )

        response = temp_state[
            "messages"
        ][0]

    return {
        "messages": [
            response
        ]
    }


# ============================================================
# TOOL NODE
# ============================================================

tool_node = ToolNode(
    TOOLS
)


# ============================================================
# ROUTING
# ============================================================

def should_continue(
    state: AgentState,
):
    """
    Decide whether tools need to execute.
    """

    if not state["messages"]:
        return END

    last_message = state[
        "messages"
    ][-1]

    if isinstance(
        last_message,
        AIMessage,
    ):

        if getattr(
            last_message,
            "tool_calls",
            None,
        ):

            return "tools"

    return END


# ============================================================
# GRAPH
# ============================================================

workflow = StateGraph(
    AgentState
)

workflow.add_node(
    "agent",
    authenticated_agent_node,
)

workflow.add_node(
    "tools",
    tool_node,
)

workflow.set_entry_point(
    "agent"
)

workflow.add_conditional_edges(
    "agent",
    should_continue,
)

workflow.add_edge(
    "tools",
    "agent"
)

graph = workflow.compile()


# ============================================================
# HISTORY NORMALIZATION
# ============================================================

def normalize_history(
    history: list | None,
) -> list[BaseMessage]:
    """
    Convert frontend history into LangChain messages.

    Only the most recent MAX_HISTORY messages
    are retained.
    """

    messages = []

    if not history:
        return messages

    # --------------------------------------------------------
    # Keep only the latest 15 messages
    # --------------------------------------------------------

    history = history[-MAX_HISTORY:]

    for item in history:

        if not isinstance(
            item,
            dict,
        ):
            continue

        role = item.get(
            "role"
        )

        content = item.get(
            "content",
            "",
        )

        if not isinstance(
            content,
            str,
        ):
            continue

        content = content.strip()

        if not content:
            continue

        if role == "user":

            messages.append(
                HumanMessage(
                    content=content
                )
            )

        elif role == "assistant":

            messages.append(
                AIMessage(
                    content=content
                )
            )

    return messages


# ============================================================
# FINAL RESPONSE
# ============================================================

def extract_final_reply(
    messages: list[BaseMessage],
) -> str:
    """
    Extract the final natural-language
    assistant response.
    """

    for msg in reversed(
        messages
    ):

        if not isinstance(
            msg,
            AIMessage,
        ):
            continue

        if getattr(
            msg,
            "tool_calls",
            None,
        ):
            continue

        content = msg.content

        if isinstance(
            content,
            str,
        ):

            if content.strip():
                return content.strip()

        elif content:

            return str(content)

    return (
        "I couldn't generate a response. "
        "Please try again."
    )


# ============================================================
# TOOL CALL EXTRACTION
# ============================================================

def extract_tool_calls(
    messages: list[BaseMessage],
) -> list[dict]:
    """
    Extract tool calls for debugging.
    """

    result = []

    for msg in messages:

        if not isinstance(
            msg,
            AIMessage,
        ):
            continue

        calls = getattr(
            msg,
            "tool_calls",
            [],
        )

        for call in calls:

            if not isinstance(
                call,
                dict,
            ):
                continue

            args = call.get(
                "args",
                {},
            )

            if not isinstance(
                args,
                dict,
            ):
                args = {}

            result.append(
                {
                    "tool": call.get(
                        "name",
                        "unknown",
                    ),
                    "input": args,
                }
            )

    return result


# ============================================================
# CLEAN HISTORY
# ============================================================

def build_clean_history(
    messages: list[BaseMessage],
) -> list[dict]:
    """
    Remove internal tool messages and
    return frontend-friendly history.

    The returned history is also limited
    to MAX_HISTORY messages.
    """

    history = []

    for msg in messages:

        if isinstance(
            msg,
            HumanMessage,
        ):

            content = msg.content

            if (
                isinstance(
                    content,
                    str,
                )
                and content.strip()
            ):

                history.append(
                    {
                        "role": "user",
                        "content": content,
                    }
                )

        elif isinstance(
            msg,
            AIMessage,
        ):

            if getattr(
                msg,
                "tool_calls",
                None,
            ):
                continue

            content = msg.content

            if (
                isinstance(
                    content,
                    str,
                )
                and content.strip()
            ):

                history.append(
                    {
                        "role": "assistant",
                        "content": content,
                    }
                )

    # --------------------------------------------------------
    # Keep only latest 15 messages
    # --------------------------------------------------------

    return history[-MAX_HISTORY:]


# ============================================================
# PUBLIC API
# ============================================================

def run_agent(
    message: str,
    student_id: str,
    history: list | None = None,
):
    """
    Run MindSync for an authenticated student.

    Conversation history is limited to the
    latest MAX_HISTORY messages.
    """

    # --------------------------------------------------------
    # Validate message
    # --------------------------------------------------------

    if not isinstance(
        message,
        str,
    ):
        message = str(message)

    message = message.strip()

    if not message:

        return {
            "reply": "Please enter a message.",
            "history": [],
            "tool_calls": [],
            "message_count": 0,
            "message_types": [],
        }

    # --------------------------------------------------------
    # Validate student ID
    # --------------------------------------------------------

    if not isinstance(
        student_id,
        str,
    ):
        student_id = str(student_id)

    student_id = student_id.strip()

    if not student_id:

        return {
            "reply": (
                "I couldn't identify "
                "your student account."
            ),
            "history": [],
            "tool_calls": [],
            "message_count": 0,
            "message_types": [],
        }

    # --------------------------------------------------------
    # Build messages
    # --------------------------------------------------------

    messages = normalize_history(
        history
    )

    # --------------------------------------------------------
    # Add current user message
    # --------------------------------------------------------

    messages.append(
        HumanMessage(
            content=message
        )
    )

    # --------------------------------------------------------
    # Final safety limit
    #
    # history can contain 15 messages + current message.
    # Keep total conversational messages at 15.
    # --------------------------------------------------------

    messages = messages[-MAX_HISTORY:]

    # --------------------------------------------------------
    # Authenticated context
    # --------------------------------------------------------

    context = AgentContext(
        student_id=student_id
    )

    # --------------------------------------------------------
    # Run LangGraph
    # --------------------------------------------------------

    result = graph.invoke(
        {
            "messages": messages
        },
        context=context,
        config={
            "recursion_limit": MAX_RECURSION_LIMIT
        },
    )

    result_messages = result.get(
        "messages",
        [],
    )

    # --------------------------------------------------------
    # Extract response
    # --------------------------------------------------------

    reply = extract_final_reply(
        result_messages
    )

    # --------------------------------------------------------
    # Extract tools
    # --------------------------------------------------------

    tool_calls = extract_tool_calls(
        result_messages
    )

    # --------------------------------------------------------
    # Clean history
    # --------------------------------------------------------

    output_history = build_clean_history(
        result_messages
    )

    # --------------------------------------------------------
    # Return
    # --------------------------------------------------------

    return {
        "reply": reply,
        "history": output_history,
        "tool_calls": tool_calls,
        "message_count": len(
            result_messages
        ),
        "message_types": [
            type(msg).__name__
            for msg in result_messages
        ],
    }